export const GET_ERRORS = "GET_ERRORS";
export const GET_PATIENTS = "GET_PATIENTS";
export const GET_PATIENT = "GET_PATIENT";
export const DELETE_PATIENT = "DELETE_PROJECT";
export const SEND_META_DATA = "SEND_META_DATA";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
